version: 1.0.3

signing:
  debug:
    store: $MOD_HOME/res/ingress-mod.keystore
    pass: qwerty
    alias: ingress_mod

  release:
    store: $MOD_HOME/res/ingress-mod.keystore
    pass: qwerty
    alias: ingress_mod

assets:
  data:
    caption: Original normal
  data-xhdpi:
    caption: Original xhdpi
    parent: normal
  data-xxhdpi:
    caption: Original xxhdpi
    parent: xhdpi
  data-hvga:
    caption: Mod HVGA
  data-qvga:
    caption: Mod QVGA
  data-ingressopt-hvga:
    caption: Ingressopt HVGA
  data-ingressopt-qvga:
    caption: Ingressopt QVGA

maps_key:
  debug: AIzaSyDnBplgAJZudNKNy7n2xwfvcHnrZuVVGsk
  release: AIzaSyDnBplgAJZudNKNy7n2xwfvcHnrZuVVGsk
